name: Build/test
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
      c: ${{ steps.changes.outputs.c }}
      gen: ${{ steps.changes.outputs.gen }}
    steps:
      - name: checkout tree-sitter-coalton
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Get changed files
        id: changes
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "c=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.\(c\|h\)$' | xargs)" >> $GITHUB_OUTPUT
          # Generated C code
          echo "gen=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.\(c\|h\)$' | grep -v 'src/scanner.c' | xargs)" >> $GITHUB_OUTPUT
  test:
    runs-on: ${{ matrix.os }}
    needs: changedfiles
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: checkout tree-sitter-coalton
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate parser from scratch and test it
        if: ${{ runner.os == 'Linux' || needs.changedfiles.outputs.c }}
        shell: bash
        run: |
          npm install
          npm test

      - name: Check fidelity of checked-in C code
        if: ${{ runner.os == 'Linux' && needs.changedfiles.outputs.gen }}
        shell: bash
        run: |
          # `git diff --quiet` doesn't seem to work on Github Actions
          changes=$(git diff --name-only --diff-filter=ACMRT | xargs)
          if [ ! -z "$changes" ]; then
            echo "::error file=grammar.js::Generated $changes differs from the checked in version"
            git diff --exit-code
            exit 1
          fi
